version: "3"
services:

  web:
    restart: always
    build: .
    command: bash -c "flask db upgrade && flask run --host=0.0.0.0"
    environment:
      - FLASK_APP=microblog.py
      - DATABASE_URL=postgresql://postgres:pgpwd@db:5432
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  # data:
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   command: "true"

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pgpwd
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"